name: adam_fauzan_frond_end
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  flutter_iconly: ^1.0.2
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^9.0.0
  freezed: ^2.3.2
  get: ^4.6.5
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  image_cropper: ^3.0.2
  image_picker: ^0.8.7
  intl: ^0.18.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  logger: ^1.2.2
  lottie: ^2.3.1
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^3.0.3
  path: ^1.9.0
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  pinput: ^2.2.31
  pull_to_refresh: ^2.0.0
  retrofit: any
  retrofit_generator: any
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  sizer: ^2.0.15
  sqflite: ^2.3.3+1

dev_dependencies:
  build_runner: any
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/resources/

flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/